
export const FETCH_GAMES_LOADING = "FETCH_GAMES_LOADING"
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS"
export const FETCH_GAMES_FAILED = "FETCH_GAMES_FAILED"
export const SEARCH_GAMES_BY_NAME = "SEARCH_GAMES_BY_NAME"
export const FILTER_GAMES_BY_GROUP = "FILTER_GAMES_BY_GROUP"
export const FILTER_GAMES_BY_LEVEL = "FILTER_GAMES_BY_LEVEL"